export {
  // LGA lookups
  LGA_HOUSEHOLD_SIZE,
  LGA_GROWTH_RATE_PCT,
  getDefaults,
  // Demographic
  ABS_AVG_HOUSEHOLD_SIZE,
  ABS_GROWTH_RATE_PCT,
  // Economic
  FTE_PER_MILLION,
  RESIDENTIAL_FTE,
  COMMERCIAL_DENSITY_M2,
  RETAIL_SPEND_PER_PERSON,
  AVG_SALARY,
  // Environmental
  CO2E_RESIDENTIAL_PER_DW,
  CO2E_COMMERCIAL_PER_M2,
  WATER_DEMAND_PER_DW_ML,
  RUNOFF_COEFFICIENT,
  TREE_REPLACEMENT_RATIO,
  DEFAULT_RAINFALL_MM,
  // Sustainability
  DWELLING_SIZE_M2,
  DENSITY_THRESHOLD_DW_HA,
} from "./constants";

export type { LgaDefaults } from "./constants";
